import type { ClassifiedChange } from '../analyzers/severity-classifier.js'

export interface PrCommentInput {
  owner: string
  repo: string
  prNumber: number
  baseSha: string
  headSha: string
}

export interface PrCheckResult {
  passed: boolean
  summary: string
  blockingChanges: ClassifiedChange[]
  warnings: ClassifiedChange[]
}

export function evaluatePreShipGate(
  changes: ClassifiedChange[],
): PrCheckResult {
  const blocking = changes.filter(c => c.severity === 'critical')
  const warnings = changes.filter(c => c.severity === 'high' || c.severity === 'medium')

  if (blocking.length > 0) {
    return {
      passed: false,
      summary: `❌ Blocked: ${blocking.length} critical dependency change(s) detected. Manual review required before merge.`,
      blockingChanges: blocking,
      warnings,
    }
  }

  if (changes.some(c => c.severity === 'high')) {
    return {
      passed: true,
      summary: `⚠️ Warning: ${warnings.length} dependency change(s) need review, but no blocking issues.`,
      blockingChanges: [],
      warnings,
    }
  }

  return {
    passed: true,
    summary: `✅ All ${changes.length} tracked dependencies are safe to update.`,
    blockingChanges: [],
    warnings: [],
  }
}

export function formatPrComment(result: PrCheckResult): string {
  const lines: string[] = [
    '## Dependency Change Check',
    '',
    result.summary,
    '',
  ]

  if (result.blockingChanges.length > 0) {
    lines.push('### 🚫 Blocking Changes', '')
    for (const c of result.blockingChanges) {
      lines.push(`- **${c.packageName}** \`${c.fromVersion} → ${c.toVersion}\` (${c.severity})`)
      for (const r of c.reasons) {
        lines.push(`  - ${r}`)
      }
    }
    lines.push('')
  }

  if (result.warnings.length > 0) {
    lines.push('### ⚠️ Warnings', '')
    for (const c of result.warnings) {
      lines.push(`- **${c.packageName}** \`${c.fromVersion} → ${c.toVersion}\` (${c.severity})`)
      for (const r of c.reasons) {
        lines.push(`  - ${r}`)
      }
    }
    lines.push('')
  }

  lines.push('---', '')
  lines.push('_Generated by Nightlamp Dependency Monitor_')

  return lines.join('\n')
}